# Generated by Django 3.2.15 on 2023-03-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
    ]
