# Generated by Django 3.2.15 on 2023-03-12 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolmanage', '0002_auto_20230312_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
