# Generated by Django 3.2.15 on 2023-03-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanage', '0003_alter_subjects_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanage.teacher'),
        ),
    ]
